# Do not edit. Generated by the configure script.
export PATH:=/usr/ports/www/node/work/node-v15.5.1/out/tools/bin:$(PATH)
BUILDTYPE=Release
NODE_TARGET_TYPE=executable
PYTHON=/usr/local/bin/python3.7
PREFIX=/usr/local
